# -*- coding: utf-8 -*-
"""Problema1211.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XdIH0vAqL0rWVBDQViFr6uQxL4X4IUNn
"""

# Resolución de problema de optimización usando programación lineal

from scipy.optimize import linprog
import numpy as np

# Definición de parámetros del problema
funcion_objetivo = [-150.0, -175.0]

# Restricciones del sistema (Ax <= b)
A = [[7.0, 11.0],
     [10.0, 8.0],
     [1.0, 0.0],
     [0.0, 1.0]]

b = [77.0, 80.0, 9.0, 6.0]

# Límites de las variables (x >= 0, y >= 0)
x_limites = (0.0, None)
y_limites = (0.0, None)

# Ejecución del algoritmo de optimización
resultado_optimizacion = linprog(
    c=funcion_objetivo,
    A_ub=A,
    b_ub=b,
    bounds=[x_limites, y_limites],
    method="highs"
)

# Presentación de resultados
if resultado_optimizacion.success:
    print("=" * 50)
    print("RESULTADOS DE LA OPTIMIZACIÓN")
    print("=" * 50)
    print(f"Variables óptimas: {resultado_optimizacion.x}")
    print(f"Valor óptimo alcanzado: {resultado_optimizacion.fun}")
    print("=" * 50)
else:
    print("No se encontró solución factible")