# -*- coding: utf-8 -*-
"""09SepFunc.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AjoaPBW7qzmohngmuC_KpTEwXABvEGm3
"""

import math

# Define the funtion f(x)
def f(x):
    return (9.81 * 68.1 / x) * (1 - math.exp(-x * 10 / 68.1)) - 40

def main():
    a = 14.5
    b = 15.5  # Intervalo inicial
    K = 0.0  # inicilaizar k antes del loop
    Kold = 0.0
    Err = 0.0
    Errmax = 1e-6  # Tolerance
    iter_count = 0
    maxIter = 100

    while Err > Errmax or iter_count == 0 and iter_count < maxIter:
        Kold = K                 # guardar depues de evaluar
        K = (a + b) / 2.0


        # Calcular error
        Err = abs(K - Kold)