# -*- coding: utf-8 -*-
"""Proyecto28Nov.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EJa3Cfqmmd1VxNNMRbVCA5965WXJdpC_
"""

!sudo apt-get install gcc

!gcc Euler.c -o euler -lm

!./euler

!gcc rk2.c -o rk2 -lm

!./rk2

!gcc rk4.c -o rk4 -lm

!./rk4

"""

Este es el ejemplo **Sistema masa–resorte sin fricción (oscilador armónic**"""

!gcc SistemaResorte.c -o SistemaResorte -lm

!./SistemaResorte