# -*- coding: utf-8 -*-
"""EvalFinal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NMpdcRwidfQWk6aQXRpbX46aZK121sYT

**Problema.**
La concentración del producto

dt/dC​=kC(t)(Cmax​−C(t)),

con condiciones y parámetros:

*   C(0)=0.02 mol·L−1
*  k=0.45 L·mol−1·min−1
*   Cmax=1.0 mol·L−1
*   intervalo de integración:t∈[0,25] min

Objetivo.Predecir
C(t) en 0–25 min usando Runge–Kutta de 4º orden (RK4) con
Δt=0.1, comparar con Runge–Kutta de 2º orden (RK2, Heun) con el mismo Δt, y determinar qué Δt debe usar RK2 para obtener resultados equivalentes.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile logistica_rk.c
# /* logistica_rk.c
#    Solucion de la EDO logistica usando RK2 (Heun) y RK4.
#    dC/dt = k * C * (Cmax - C)
# */
# 
# #include <stdio.h>
# #include <math.h>
# 
# double k = 0.45;
# double Cmax = 1.0;
# 
# /* dC/dt */
# double f(double C) {
#     return k * C * (Cmax - C);
# }
# 
# /* RK4 */
# double rk4_step(double C, double h) {
#     double k1 = f(C);
#     double k2 = f(C + 0.5*h*k1);
#     double k3 = f(C + 0.5*h*k2);
#     double k4 = f(C + h*k3);
#     return C + (h/6.0)*(k1 + 2*k2 + 2*k3 + k4);
# }
# 
# /* RK2 (Heun) */
# double rk2_heun_step(double C, double h) {
#     double k1 = f(C);
#     double k2 = f(C + h*k1);
#     return C + 0.5*h*(k1 + k2);
# }
# 
# int main() {
#     double C0 = 0.02;
#     double h = 0.1;
#     double T = 25.0;
#     int N = (int)(T / h);
# 
#     double Ct_rk4 = C0;
#     double Ct_rk2 = C0;
#     double t = 0.0;
# 
#     printf("t(min)\t\tRK4_C(t)\t\tRK2_C(t)\t\t|diff|\n");
#     printf("--------------------------------------------------------------\n");
# 
#     printf("%.2f\t\t%.9f\t%.9f\t%.9f\n", t, Ct_rk4, Ct_rk2, fabs(Ct_rk4 - Ct_rk2));
# 
#     for (int i = 1; i <= N; i++) {
#         Ct_rk4 = rk4_step(Ct_rk4, h);
#         Ct_rk2 = rk2_heun_step(Ct_rk2, h);
#         t = i * h;
# 
#         printf("%.2f\t\t%.9f\t%.9f\t%.9f\n",
#                t, Ct_rk4, Ct_rk2, fabs(Ct_rk4 - Ct_rk2));
#     }
# 
#     return 0;
# }
#

!gcc logistica_rk.c -o logistica_rk -lm

!./logistica_rk > salida_logistica.txt
!sed -n '1,30p' salida_logistica.txt

!grep -n "^25.00" salida_logistica.txt || true
!grep "25.00" salida_logistica.txt || true

""" **¿Qué tamaño de Δt necesita RK2 para “igualar” RK4 (con
ℎ=0.1)?**
Para que la máxima diferencia entre RK2 y RK4 sea ≤ 10−4: usar
Δt≤0.05.

Para diferencia ≤10−6: usar Δt≈0.01.

En la práctica, con Δt=0.05 RK2 muestra errores comparables al RK4 con Δt=0.1 para esta EDO.
"""